version: '3'
services:

  tests:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile-tests
    depends_on:
      - bookings
      - users
      - restaurants
    volumes:
      - ./ApiGateway/ApiGateway:/usr/src/app/ApiGateway

  bookings:
    build:
      context: ./BookingService
      dockerfile: Dockerfile
    environment:
      - "CONFIG=FAILURE_TEST"
    ports:
      - "8082:8080"

  users:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    environment:
      - "CONFIG=TEST"
    ports:
      - "8081:8081"

  restaurants:
    build:
      context: ./RestaurantService
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: db-testing
        target: /usr/src/app/restaurants/db
    depends_on:
      - redis
      - worker
    ports:
      - "8083:8080"
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=FAILURE_TEST"
  worker:
    build:
      context: ./RestaurantService
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=TEST"
    command: celery -A restaurants.worker:celery worker -l info -B -s /tmp/celerybeat-schedule
    depends_on:
      - redis
    volumes:
      - type: volume
        source: db-testing
        target: /usr/src/app/restaurants/db
  redis:
    image: "redis:alpine"
    expose:
      - "6379"

volumes:
    db-testing: