version: '3'
services:

  tests:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile-tests
    depends_on:
      - bookings
      - users
    volumes:
      - ./ApiGateway/ApiGateway:/usr/src/app/ApiGateway

  bookings:
    build:
      context: ./BookingService
      dockerfile: Dockerfile
    environment:
      - "CONFIG=FAILURE_TEST"
    ports:
      - "8082:8080"

  users:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    environment:
      - "CONFIG=TEST"
    ports:
      - "8081:8081"