version: '3'
services:

  bookings:
    build:
      context: ./BookingService
      dockerfile: Dockerfile
    environment:
      - "CONFIG=FAILURE_TEST"
    ports:
      - "8082:8080"

  users:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    environment:
      - "CONFIG=TEST"
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./GoOutSafe
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    depends_on:
      - api

  api:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    depends_on:
      - bookings
      - users
      - restaurants

  nginx:
    image: nginx
    build:
      context : ./nginx/
      dockerfile: nginx.dockerfile
    depends_on:
      - api
    restart: always
    ports:
      - "8080:80"

  restaurants:
    build:
      context: ./RestaurantService
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: db-production
        target: /code/monolith/db
    depends_on:
      - redis
      - worker
    ports:
      - "8083:8080"
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=DOCKER"
  worker:
    build:
      context: ./RestaurantService
    environment:
      - "BROKER=redis://redis:6379"
      - "BACKEND=redis://redis:6379"
      - "CONFIG=PRODUCTION"
    command: celery -A monolith.worker:celery worker -l info -B -s /tmp/celerybeat-schedule
    depends_on:
      - redis
    volumes:
      - type: volume
        source: db-production
        target: /code/monolith/db
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  db-production: